accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

movie_crud/urls.py
from django.urls import path
from . import views

app_name = "movie_crud"
urlpatterns = [
    path("", views.main, name="main"),
    path("index/", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviews/', include('movie_crud.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

movie_crud/models.py
from distutils.command.upload import upload
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    movie_name = models.CharField(max_length=80)
    grade = models.FloatField(
        validators=[MinValueValidator(0.0), MaxValueValidator(5.0)],
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(blank=True, upload_to='image/')

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

movie_crud/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "__all__"
        labels = {
            'title': '리뷰제목',
            'content': '리뷰내용',
            'movie_name': '영화제목',
            'grade': '평점',
        }

        error_messages = {
            'grade': {
                'min_value':'0점이하는 지정할 수 없습니다.',
                'max_value':'5점을 초과하여 지정할 수 없습니다.'
            }
        }

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movie_crud:main')
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        login_form = AuthenticationForm(request, data=request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect(request.GET.get('next') or 'movie_crud:main')
    else:
        login_form = AuthenticationForm()
    context = {
    'login_form': login_form,
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('movie_crud:main')

movie_crud/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Review
from .forms import ReviewForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def main(request):
    reviews = Review.objects.all().order_by("-pk")
    context = {
        "reviews": reviews,
    }
    return render(request, "movie_crud/main.html", context)


def index(request):
    reviews = Review.objects.all().order_by("-pk")
    context = {
        "reviews": reviews,
    }
    return render(request, "movie_crud/index.html", context)

@login_required
def create(request):
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("movie_crud:index")
    else:
        form = ReviewForm()
    context = {
        "review_form": form,
    }
    return render(request, "movie_crud/update.html", context)


def detail(request, pk):
    review_detail = Review.objects.get(id=pk)
    context = {
        "review_detail": review_detail,
    }
    return render(request, "movie_crud/detail.html", context)

@login_required
def update(request, pk):
    review = get_object_or_404(Review, pk=pk)

    if request.method == "POST":
        review_form = ReviewForm(request.POST, request.FILES, instance=review)
        if review_form.is_valid():
            review_form.save()
            return redirect("movie_crud:detail", review.pk)
    else:
        review_form = ReviewForm(instance=review)
    context = {
        "review" : review,
        "review_form": review_form
        }
    return render(request, "movie_crud/update.html", context)

@login_required
def delete(request, pk):
    Review.objects.get(id=pk).delete()
    return redirect("movie_crud:index")

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block navbaricon %}
  {% load static %}
  <img src="{% static "movie_crud/img/123.png" %}" alt="" width="30" height="30" class="d-inline-block align-text-top"/>
{% endblock navbaricon %}

{% block content %}
  {% load django_bootstrap5 %}
  <h1>로그인</h1>
  <form action="" method='POST'>
    {% csrf_token %}
    <!-- 부트스트랩 리뷰폼 -->
    {% bootstrap_form login_form %}
    <input type="submit" value="로그인">
    <button>
      <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
    </button>
  </form>
  <script src="{% static 'movie_crud/js/movie_crud.js' %}"/>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block navbaricon %}
  {% load static %}
  <img src="{% static "movie_crud/img/123.png" %}" alt="" width="30" height="30" class="d-inline-block align-text-top"/>
{% endblock navbaricon %}

{% block content %}
  {% load django_bootstrap5 %}
  <h1>회원가입</h1>
  <form action="" method='POST'>
    {% csrf_token %}
    <!-- 부트스트랩 리뷰폼 -->
    {% bootstrap_form form %}
    <input type="submit" value="제출">
  </form>
  <script src="{% static 'movie_crud/js/movie_crud.js' %}"/>
{% endblock content %}

movie_crud/templates/movie_crud/create.html
{% extends 'base.html' %}

{% block navbaricon %}
  {% load static %}
  <img src="{% static "movie_crud/img/123.png" %}" alt="" width="30" height="30" class="d-inline-block align-text-top"/>
{% endblock navbaricon %}

{% block content %}
  {% load django_bootstrap5 %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-primary" type="submit" value="추가">
  </form>
  <script src="{% static 'movie_crud/js/movie_crud.js' %}"/>
{% endblock %}

movie_crud/templates/movie_crud/detail.html
{% extends 'base.html' %}

{% block navbaricon %}
  {% load static %}
  <img src="{% static "movie_crud/img/123.png" %}" alt="" width="30" height="30" class="d-inline-block align-text-top"/>
{% endblock navbaricon %}

{% block content %}
  <div class="mb-3 px-3">
    <img src="{{ review_detail.image.url }}" alt="">
    <h1>리뷰</h1>
    <h3>영화 제목 :
      {{ review_detail.movie_name }}
    </h3>
    <h3>영화 평점 :
      {{ review_detail.grade }}
    </h3>
    <p>리뷰 제목 :
      {{ review_detail.title }}
    </p>
    <p>리뷰 내용 :
      {{ review_detail.content }}
    </p>
    <p>리뷰 생성시간 :
      {{ review_detail.created_at }}
    </p>
    <p>리뷰 수정시간 :
      {{ review_detail.updated_at }}
    </p>
    <a href="{% url 'movie_crud:update' review_detail.pk %}"><input type="submit" class="btn btn-warning " value="수정"></a>
    <a href="{% url 'movie_crud:delete' review_detail.pk %}"><input type="submit" class="btn btn-danger" value="삭제"></a>
  </div>
  <script src="{% static 'movie_crud/js/movie_crud.js' %}"/>
{% endblock %}

movie_crud/templates/movie_crud/index.html
{% extends 'base.html' %}

{% block navbaricon %}
  {% load static %}
  <img src="{% static "movie_crud/img/123.png" %}" alt="" width="30" height="30" class="d-inline-block align-text-top"/>
{% endblock navbaricon %}

{% block content %}
  <h1>게시판</h1>
  <div class="table-responsive input-group justify-content-center">

    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">리뷰 제목</th>
          <th scope="col">리뷰 내용</th>
          <th scope="col">영화 이름</th>
          <th scope="col">영화 평점</th>
          <th scope="col">리뷰 수정</th>
        </tr>
      </thead>
      <tbody>
        {% for review in reviews %}
          <tr>
            <th scope="row">{{ review.pk }}</th>
            <td>
              <a href="{% url 'movie_crud:detail' review.pk %}">{{ review.title }}</a>
            </td>
            <td>{{ review.content }}</td>
            <td>{{ review.movie_name }}</td>
            <td>{{ review.grade }}</td>
            <td>{{ review.updated_at|date:"y/m/d  H:i" }}</td>
            <td>
              <a class="btn btn-primary py-sm-1" href="{% url 'movie_crud:update' review.pk %}" role="button">변경</a>
            </td>
            <td>
              <a class="btn btn-danger py-sm-1" href="{% url 'movie_crud:delete' review.pk %}" role="button">삭제</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="row">
    <div class="col-4"></div>
    <div class="col-4 d-flex justify-content-center">
      <nav aria-label="Page navigation example">
        <ul class="pagination">
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">1</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">3</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
    <div class="col-4 d-flex justify-content-end">
      <a class="btn btn-secondary" href="{% url 'movie_crud:create' %}" role="button" style="height: 2.5rem">리뷰작성</a>
    </div>
  </div>
  <script src="{% static 'movie_crud/js/movie_crud.js' %}"/>
{% endblock %}

movie_crud/templates/movie_crud/main.html
{% extends 'base.html' %}
{% load static %}

{% block navbaricon %}
  <link rel="stylesheet" href="{% static 'movie_crud/css/style.css' %}">
  <img src="{% static "movie_crud/img/123.png" %}" alt="" width="30" height="30" class="d-inline-block align-text-top"/>
{% endblock navbaricon %}

{% block carousel%}
  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>

    <div class="carousel-inner">
      <div class="carousel-item active">
        <a href="{% url 'movie_crud:create' %}">
          <img src="{% static 'movie_crud/img/topgun.jpg' %}" class="d-block" alt="...">
        </a>
      </div>
      <div class="carousel-item">
        <img src="{% static 'movie_crud/img/123.png' %}" class="d-block" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'movie_crud/img/spider.jpg' %}" class="d-block" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
{% endblock carousel%}

{% block content %}
  <div class="container text-center">
    <h1 class="d-inline">메인페이지</h1>
    <div>
      <a href="{% url 'movie_crud:index' %}"><input class="btn btn-primary" type="submit" value="리뷰 목록"></a>
      <a href="{% url 'movie_crud:create' %}"><input class="btn btn-primary" type="submit" value="리뷰 작성"></a>
    </div>
    {% for review in reviews %}
      <div class="card" style="width: 18rem;">
        <img src="{{ review.image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ review.title }}</h5>
          <p class="card-text">{{ review.content }}</p>
          <a href="{% url 'movie_crud:detail' review.pk %}" class="btn btn-primary">자세히보기</a>
        </div>
      </div>
    {% endfor %}
  </div>

  <script src="{% static 'movie_crud/js/movie_crud.js' %}"/>
{% endblock %}

movie_crud/templates/movie_crud/update.html
{% extends 'base.html' %}

{% block navbaricon %}
  {% load static %}
  <img src="{% static "movie_crud/img/123.png" %}" alt="" width="30" height="30" class="d-inline-block align-text-top"/>
{% endblock navbaricon %}

{% block content %}
  <!-- 페이지 설명 -->
  {% if request.resolver_match.url_name == 'create' %}
    <h1>리뷰작성하기</h1>
  {% else %}
    <h1>수정하기</h1>
  {% endif %}

  <!-- 제출 폼 -->
  {% load django_bootstrap5 %}
  <form action="" method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    <!-- 부트스트랩 리뷰폼 -->
    {% bootstrap_form review_form %}
    {% comment %} <input type="file" accept="image/*" name="" id=""> {% endcomment %}
    <!-- 수제 리뷰폼 -->
    {% comment %} {% for field in review_form %}
      <div>
        {{ field.label_tag }}
      </div>
      {{ field }}
      {{ field.errors }}
    {% endfor %} {% endcomment %}

    <!-- 작성/ 수정 버튼 -->
    {% if request.resolver_match.url_name == 'create' %}
      {% bootstrap_button content='리뷰작성' button_type='submit' button_class="btn-primary" %}
    {% else %}
      {% bootstrap_button content='수정하기' button_type='submit' button_class="btn-primary" %}
    {% endif %}

  </form>
  <script src="{% static 'movie_crud/js/movie_crud.js' %}"/>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% block js %}{% endblock js %}
    {% comment %} <link rel="stylesheet" href="{% static 'movie_crud/css/style.css' %}"> {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'movie_crud:main' %}">
          {% block navbaricon %}{% endblock navbaricon %}
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'movie_crud:index' %}">리뷰목록</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movie_crud:create' %}">리뷰작성</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
              </li>
              <li class="nav-item">
                <p class="nav-link mb-0 fw-bold">{{ user }}님 안녕하세요!</p>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% block carousel%}{% endblock carousel%}
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>

</html>